#pragma config(Sensor, S1, distance, sensorEV3_Ultrasonic)
#pragma config(Motor, motorB, arm, tmotorEV3_Medium, PIDControl, reversed, encoder)
#pragma config(Motor, motorC, right, tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor, motorD, left, tmotorEV3_Large, PIDControl, encoder)
//!!Code automatically generated by 'ROBOTC' configuration wizard
// My name is dennis           !!//
void snurr()
{
    setMotorSpeed(left, 100);
    setMotorSpeed(right, -100);
    wait1Msec(2000);
    setMotorSpeed(left, 0);
    setMotorSpeed(right, 0);
}

void bok()
{
    motor[arm] = 50;
    wait1Msec(1000);
    motor[arm] = 0;
}

void bokback()
{
    motor[arm] = -50;
    wait1Msec(1000);
    motor[arm] = 0;
}
task main()
{
    while (getUSDistance(distance) > 50)
    {
        //Move the robot forward
        setMotorSpeed(left, 50);
        setMotorSpeed(right, 50);
    }

    //Stop the motors
    setMotorSpeed(left, 0);
    setMotorSpeed(right, 0);
    snurr();
    bok();
    bokback();
    while (getUSDistance(distance) > 50)
    {
        //Move the robot forward
        setMotorSpeed(left, 50);
        setMotorSpeed(right, 50);
    }
}
