#pragma config(Sensor, S1, distance, sensorEV3_Ultrasonic)
#pragma config(Motor, motorB, arm, tmotorEV3_Medium, PIDControl, reversed, encoder)
#pragma config(Motor, motorC, right, tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor, motorD, left, tmotorEV3_Large, PIDControl, encoder)
//!!Code automatically generated by 'ROBOTC' configuration wizard

void find_wall()
{
	int wall_distance[360];
	bool search_for_wall = true;
	//int degrees;

	while(getGyroDegrees(S1) <= 360){
		setMotorSpeed(left, 50);
		setMotorSpeed(right, 0);

		for(int i = 0; i < 360; i++){
			wall_distance[i] = getUSDistance(S2);
		}
	}
	int samllest_distance = wall_distance[0];

	for(i = 0; i < 360; i++){
		if(wall_distance[i] < smallest_distance){
			smallest_distance = wall_distance[i];
		}
	}


	while(search_for_wall == true){
		setMotorSpeed(left, 50);
		setMotorSpeed(right, 0);
		if(getUSDistance(S2) == smallest_distance)
		{
			bool run = false;
		}
	}
}

task main()
{
		find_wall();
}
